/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "add4.v:1" *)
module add4(in1, in2, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "add4.v:2" *)
  input [3:0] in1;
  (* src = "add4.v:3" *)
  input [3:0] in2;
  (* src = "add4.v:4" *)
  output [3:0] out;
  assign _00_ = ~(in2[1] ^ in1[1]);
  assign _01_ = ~(in2[0] & in1[0]);
  assign out[1] = _01_ ^ _00_;
  assign _02_ = in2[2] ^ in1[2];
  assign _03_ = ~(in2[1] & in1[1]);
  assign _04_ = ~((_01_ | _00_) & _03_);
  assign out[2] = _04_ ^ _02_;
  assign _05_ = ~(in2[3] ^ in1[3]);
  assign _06_ = in2[2] & in1[2];
  assign _07_ = ~((_04_ & _02_) | _06_);
  assign out[3] = _07_ ^ _05_;
  assign out[0] = in2[0] ^ in1[0];
endmodule
