/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "conditional_decode.v:1" *)
module conditional_logic(key, a, b, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "conditional_decode.v:3" *)
  input [7:0] a;
  (* src = "conditional_decode.v:4" *)
  input [7:0] b;
  (* src = "conditional_decode.v:2" *)
  input [7:0] key;
  (* src = "conditional_decode.v:5" *)
  output [7:0] out;
  assign _00_ = b[0] ^ a[0];
  assign _01_ = ~(key[7] | key[6]);
  assign _02_ = key[6] & ~(key[7]);
  assign _03_ = key[5] | key[4];
  assign _04_ = _02_ & ~(_03_);
  assign _05_ = ~(key[3] | key[2]);
  assign _06_ = _05_ & ~(key[1]);
  assign _07_ = ~((_06_ & _04_) | _01_);
  assign _08_ = b[0] & a[0];
  assign out[0] = _07_ ? _00_ : _08_;
  assign _09_ = b[1] ^ a[1];
  assign _10_ = b[1] & a[1];
  assign out[1] = _07_ ? _09_ : _10_;
  assign _11_ = b[2] ^ a[2];
  assign _12_ = b[2] & a[2];
  assign out[2] = _07_ ? _11_ : _12_;
  assign _13_ = b[3] ^ a[3];
  assign _14_ = b[3] & a[3];
  assign out[3] = _07_ ? _13_ : _14_;
  assign _15_ = b[4] ^ a[4];
  assign _16_ = b[4] & a[4];
  assign out[4] = _07_ ? _15_ : _16_;
  assign _17_ = b[5] ^ a[5];
  assign _18_ = b[5] & a[5];
  assign out[5] = _07_ ? _17_ : _18_;
  assign _19_ = b[6] ^ a[6];
  assign _20_ = b[6] & a[6];
  assign out[6] = _07_ ? _19_ : _20_;
  assign _21_ = b[7] ^ a[7];
  assign _22_ = b[7] & a[7];
  assign out[7] = _07_ ? _21_ : _22_;
endmodule

(* src = "add8.v:1" *)
module lol(in1, in2, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "add8.v:2" *)
  input [4:0] in1;
  (* src = "add8.v:3" *)
  input [4:0] in2;
  (* src = "add8.v:4" *)
  output [4:0] out;
  assign _00_ = in1[0] & in2[0];
  assign _01_ = in1[1] ^ in2[1];
  assign out[1] = _01_ ^ _00_;
  assign _02_ = in1[1] & in2[1];
  assign _03_ = ~((_01_ & _00_) | _02_);
  assign _04_ = ~(in1[2] ^ in2[2]);
  assign out[2] = _04_ ^ _03_;
  assign _05_ = ~(in1[2] & in2[2]);
  assign _06_ = ~((_04_ | _03_) & _05_);
  assign _07_ = in1[3] ^ in2[3];
  assign out[3] = _07_ ^ _06_;
  assign _08_ = in1[2] & in2[2];
  assign _09_ = in1[3] & in2[3];
  assign _10_ = ~((_07_ & _08_) | _09_);
  assign _11_ = _04_ | ~(_07_);
  assign _12_ = ~((_11_ | _03_) & _10_);
  assign _13_ = in1[4] ^ in2[4];
  assign out[4] = _13_ ^ _12_;
  assign out[0] = in1[0] ^ in2[0];
endmodule
