// Code generated by "EggBackend.cs"; DO NOT EDIT.
#![allow(warnings)]
use egg::{rewrite, Applier, Id, PatternAst, Subst, Symbol, Var};

use crate::simple_ast::{
    as_constant, eqmod, get_known_zeroes, get_width, is_const, AstData, EEGraph, MbaAnalysis,
    Predicate, Rewrite, SimpleAst,
};

pub fn get_generated_rules() -> Vec<Rewrite> {
    vec![
        // (a:i64|b:i64) => (b:i64|a:i64)
        rewrite!("test_rule"; "(| ?a ?b)" => {
            applier_rule_test_rule {
                b : "?b".parse().unwrap(),
                a : "?a".parse().unwrap(),
            }
        } if (rule_test_rule_precondition("?a", "?b"))),
    ]
}

pub fn rule_test_rule_precondition<'a>(
    a: &'a str,
    b: &'a str,
) -> impl Fn(&mut EEGraph, Id, &Subst) -> bool + 'a {
    move |egraph, _, subst| {
        let a_id = subst[a.parse().unwrap()];
        let a = &egraph[a_id];
        let b_id = subst[b.parse().unwrap()];
        let b = &egraph[b_id];
        let precondition = ((is_const(egraph, a) && is_const(egraph, b))
            && ((get_known_zeroes(egraph, a) | get_known_zeroes(egraph, b))
                == (18446744073709551615
                    & (18446744073709551615
                        >> (64 + (get_width(egraph, a) * 18446744073709551615))))));
        if !precondition {
            return false;
        }
        return true;
    }
}

pub struct applier_rule_test_rule {
    pub b: Var,
    pub a: Var,
}

impl Applier<SimpleAst, MbaAnalysis> for applier_rule_test_rule {
    fn apply_one(
        &self,
        egraph: &mut EEGraph,
        eclass: Id,
        subst: &Subst,
        _searcher_ast: Option<&PatternAst<SimpleAst>>,
        _rule_name: Symbol,
    ) -> Vec<Id> {
        let b_id = subst[self.b];
        let bounded_width = egraph[b_id].data.width;
        let a_id = subst[self.a];
        let t2 = egraph.add(SimpleAst::Or([b_id, a_id]));

        if egraph.union(eclass, t2) {
            vec![t2]
        } else {
            vec![]
        }
    }
}
